name: C/C++ CI

on:
  push:
    branches: [ Master ]
  pull_request:
    branches: [ Master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 seanmiddleditch/gha-setup-ninja@v3
    - name: cmake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug
    - name: make
      run: make
