name: C/C++ CI

on:
  push:
    branches: [ Master ]
  pull_request:
    branches: [ Master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 seanmiddleditch/gha-setup-ninja@v3
    - name: ninja
      run: ninja
    - name: build
      run: ninja built
    - name: run
      run: ./built
