name: Makefile CI

on:
  push:
    branches: [ Master ]
  pull_request:
    branches: [ Master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build Project
      run: make
